tunnel: prospup
credentials-file: C:\Users\binet\.cloudflared\73a32dfa-e4e2-4bf1-a345-b811cd2a9666.json

ingress:
  - hostname: prospup.work
    service: http://127.0.0.1:8000
  - service: http_status:404
